export const defaultScenarios = [
  {
    name: "Günlük Ofis Çantası",
    icon: "💼",
    colorKey: "work",
    items: [
      "Laptop",
      "Laptop şarj aleti",
      "Telefon şarj kablosu",
      "Powerbank",
      "Kulaklık / headset",
      "Not defteri",
      "Kalem",
      "USB bellek / taşınabilir disk",
      "Cüzdan",
      "Kimlik ve kartlar",
      "Ev / ofis anahtarları",
      "Su şişesi",
      "Atıştırmalık (bar, kuruyemiş vb.)",
      "Islak mendil",
      "Kağıt mendil",
      "El dezenfektanı",
      "Dudak nemlendirici",
      "El kremi",
    ],
  },
  {
    name: "Spor Çantası",
    icon: "🏋️‍♀️",
    colorKey: "sport",
    items: [
      "Spor ayakkabı",
      "Spor kıyafeti (üst)",
      "Spor kıyafeti (alt)",
      "Spor sütyeni / iç çamaşırı",
      "Yedek çorap",
      "Ter havlusu",
      "Duş havlusu",
      "Duş jeli / sabun",
      "Şampuan / saç kremi (mini boy)",
      "Deodorant",
      "Saç tokası / lastik",
      "Saç fırçası / tarak",
      "Su matarası",
      "Kulaklık",
      "Spor eldiveni",
      "Kilit (dolap kilidi)",
      "Yedek tişört",
      "Küçük poşet / kirli çamaşır torbası",
    ],
  },
  {
    name: "Hafta Sonu Kaçamağı",
    icon: "🎒",
    colorKey: "travel",
    items: [
      "2 günlük kıyafet (üst)",
      "2 günlük kıyafet (alt / etek / elbise)",
      "Pijama / uyku takımı",
      "İç çamaşırı (yeterli sayıda)",
      "Çorap (yeterli sayıda)",
      "Temel bakım seti (diş fırçası, diş macunu)",
      "Yüz temizleyici / makyaj temizleme ürünleri",
      "Nemlendirici krem",
      "Deodorant",
      "Parfüm / body mist",
      "Basit makyaj çantası",
      "Saç fırçası / tarak",
      "Saç tokası / lastik / taç",
      "Telefon şarj aleti",
      "Powerbank",
      "Kimlik / pasaport",
      "Cüzdan (nakit + kartlar)",
      "Gerekli ilaçlar",
      "Mini ilk yardım (yara bandı, ağrı kesici)",
      "Islak mendil & kağıt mendil",
      "Güneş gözlüğü",
      "Küçük şemsiye / yağmurluk",
    ],
  },
  {
    name: "Düğün Günü Çantası",
    icon: "💍",
    colorKey: "wedding",
    items: [
      "Yedek ruj",
      "Yedek pudra / kompakt",
      "Küçük ayna",
      "Makyaj süngeri / fırça",
      "Transparan pudra / matlaştırıcı kağıt",
      "Mini parfüm",
      "Deodorant (mini)",
      "Saç spreyi (mini)",
      "Tel toka / firkete",
      "Saç lastiği / minik tokalar",
      "Yedek çorap / ten çorap",
      "Yedek küpe aparatı / takı minikleri",
      "Küçük dikiş seti (iğne, iplik, yedek düğme)",
      "Güvenlik iğneleri",
      "Yara bandı",
      "Ağrı kesici",
      "Islak mendil",
      "Kağıt mendil",
      "Telefon şarj kablosu",
      "Powerbank",
      "Nakit bir miktar",
      "Küçük not kağıdı + kalem",
    ],
  },
];
